### ISSUE TITLE
How to training?

### ISSUE THREAD

**Issue by cscyangj** [oawiles/X2Face#1]
I got following result.

![image](https://user-images.githubusercontent.com/25877460/46006342-dcda3100-c0e9-11e8-8071-88e8f570f5c4.png)

It seems that i need to training for new driving image? so how to do that?

thanks

**Comment by oawiles** [comment]
Hi. I'd say that the problem is probably that your crops are too different. First try recropping the images so that the face is in approximately the same place as the sample ones. This has a pretty big effect on the results. If you want to use your own crops you'd have to have access to a pretty big dataset which may or may not be feasible... 

However, if the re-cropping doesn't improve things, let me know.

**Comment by cscyangj** [comment]
@oawiles thanks， I will try and feedback to you.

**Comment by cscyangj** [comment]
@oawiles looks much better now.

![image](https://user-images.githubusercontent.com/25877460/46056015-46594e80-c181-11e8-9b00-a1e3c578b562.png)

**Comment by KeyKy** [comment]
@oawiles I got bad result [here](https://github.com/KeyKy/issue/blob/master/result_images_97.png), could you give me some advise?

**Comment by oawiles** [comment]
Hm I'm not sure: it seems to me that the person isn't changing too much (or at all?). Hence why you're getting the same output?
