### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by melih-unsal** [oawiles/X2Face#22]
Hi I get an error when I run jupyter notebook 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 0: ordinal not in range(128)

**Comment by sbyNiceBlowJob** [comment]
Same problem

**Comment by caozhenxiang-kouji** [comment]
It seems that the model is trained in python2. You will encounter this problem if you run it with python3.

**Comment by BaldrLector** [comment]
add param: encoding  = 'latin1'

**Comment by akoepke** [comment]
We have updated the code and installation instructions so that you can now use the code with python 3.7 and pytorch 0.4.1 in the 'py37_pytorch_0.4.1' branch, you will need to re-download the models from the [project page](http://www.robots.ox.ac.uk/~vgg/research/unsup_learn_watch_faces/x2face.html) again.
